backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
collections:
  - name: "posts"
    label: "Post"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Timestamp", name: "timestamp", widget: "datetime", format: "YYYY.MM.DD." }
      - { name: "permalink", widget: "hidden", default: "hirek/{{ title | slug }}/" }
      - { name: "layout", widget: "hidden", default: "layouts/post.njk" }
      - { name: "tags", widget: "hidden", default: "news" }
media_folder: src/public/images
public_folder: /images
