on: push
name: Generate static site and deploy
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Generate static site
        run: |
          npm install
          npm run build
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v3.1.2-patch
        with:
          server: ftp://ftp.yetisiszeged.hu/
          username: yetidYetisibetadeployeploy@beta.yetisiszeged.hu
          password: ${{ secrets.FTP_PWD }}
          local-dir: _site/
